# /Users/andre/.tmuxinator/tmux-config.yml

name: tmux-config
root: ~/dotfiles

windows:
  - config:
      layout: even-horizontal
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - vi tmux/.tmux.conf
        - clear
